// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYha8ZOjDYkEMfuCvliYnO3lHCxEG-k8',
    appId: '1:884409737613:web:cb9b7637d864bc3f425dc4',
    messagingSenderId: '884409737613',
    projectId: 'apartment-building-manager',
    authDomain: 'apartment-building-manager.firebaseapp.com',
    storageBucket: 'apartment-building-manager.firebasestorage.app',
    measurementId: 'G-SRDB69CK0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRGFf4wAY1txQ79niOr4pkqjiHg6JJ3Rk',
    appId: '1:884409737613:android:0488a8c8c1194037425dc4',
    messagingSenderId: '884409737613',
    projectId: 'apartment-building-manager',
    storageBucket: 'apartment-building-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrRxnKbSeAEbvNOlL_a0NRkmlODN3KV0',
    appId: '1:884409737613:ios:74065b94d47732a2425dc4',
    messagingSenderId: '884409737613',
    projectId: 'apartment-building-manager',
    storageBucket: 'apartment-building-manager.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwrRxnKbSeAEbvNOlL_a0NRkmlODN3KV0',
    appId: '1:884409737613:ios:74065b94d47732a2425dc4',
    messagingSenderId: '884409737613',
    projectId: 'apartment-building-manager',
    storageBucket: 'apartment-building-manager.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaYha8ZOjDYkEMfuCvliYnO3lHCxEG-k8',
    appId: '1:884409737613:web:066852bccef2301e425dc4',
    messagingSenderId: '884409737613',
    projectId: 'apartment-building-manager',
    authDomain: 'apartment-building-manager.firebaseapp.com',
    storageBucket: 'apartment-building-manager.firebasestorage.app',
    measurementId: 'G-4FPPJ5Y2XG',
  );

}